#!/usr/bin/env python3
"""Generate THIRD-PARTY-LICENSES.txt for binary distributions.

Binary release tarballs statically link the crates that reach the doover
binary; several are MIT/BSD-licensed, whose terms require reproducing the
license text in binary distributions (dive round 2, finding L3). This walks
the LOCKED resolve graph from the workspace, following normal and build
dependency edges only (dev-dependencies never ship), for each release
target platform, and concatenates every reached crate's license files.

Run from the workspace root (a `--locked` build must have populated the
registry cache first):  python3 scripts/third_party_licenses.py
"""

import glob
import json
import os
import subprocess
import sys

OUT = "THIRD-PARTY-LICENSES.txt"
LICENSE_GLOBS = ("LICENSE*", "LICENCE*", "COPYING*", "license*", "NOTICE*")
# the four platforms release.yml builds
TARGETS = (
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
)


def shipped_package_ids(target: str) -> tuple[set, dict]:
    """Package ids reachable from the workspace via normal/build edges."""
    meta = json.loads(
        subprocess.check_output(
            [
                "cargo",
                "metadata",
                "--format-version",
                "1",
                "--locked",
                "--filter-platform",
                target,
            ],
        )
    )
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    packages = {p["id"]: p for p in meta["packages"]}
    workspace = set(meta["workspace_members"])
    reached, stack = set(), list(workspace)
    while stack:
        nid = stack.pop()
        if nid in reached:
            continue
        reached.add(nid)
        for dep in nodes.get(nid, {}).get("deps", []):
            kinds = {k.get("kind") for k in dep.get("dep_kinds", [{}])}
            # kind None == normal; "build" ships (build scripts/proc macros
            # shape the binary); "dev" never does
            if None in kinds or "build" in kinds:
                stack.append(dep["pkg"])
    return reached - workspace, packages


def main() -> int:
    union: dict = {}
    for target in TARGETS:
        ids, packages = shipped_package_ids(target)
        for pid in ids:
            union[pid] = packages[pid]
    blocks = []
    missing = []
    for pkg in sorted(union.values(), key=lambda p: (p["name"], p["version"])):
        name, ver = pkg["name"], pkg["version"]
        spdx = pkg.get("license") or "(no SPDX expression declared)"
        src_dir = os.path.dirname(pkg["manifest_path"])
        texts = []
        if not os.path.isdir(src_dir):
            # a missing source checkout must be loud, not "(no license file)"
            # — that silence would quietly hollow the whole document out
            # (round-2 review LC4)
            print(f"ERROR: source dir missing for {name} {ver}: {src_dir}")
            print("run a `cargo build --locked` first to populate the registry")
            return 1
        for pat in LICENSE_GLOBS:
            for f in sorted(glob.glob(os.path.join(src_dir, pat))):
                if os.path.isfile(f):
                    with open(f, encoding="utf-8", errors="replace") as fh:
                        texts.append((os.path.basename(f), fh.read().strip()))
        header = f"{name} {ver} — {spdx}"
        if texts:
            body = "\n\n".join(f"--- {n} ---\n{t}" for n, t in texts)
        else:
            body = "(no license file shipped in the crate; see the SPDX expression above)"
            missing.append(f"{name} {ver} ({spdx})")
        blocks.append(f"{'=' * 78}\n{header}\n{'=' * 78}\n{body}\n")
    with open(OUT, "w", encoding="utf-8") as out:
        out.write(
            "Third-party licenses for doover binary distributions.\n"
            "Covers every crate reachable from doover via normal or build\n"
            "dependency edges in the LOCKED graph, unioned across the four\n"
            "release target platforms (dev-dependencies excluded — they are\n"
            "never linked or shipped). Generated by\n"
            "scripts/third_party_licenses.py; regenerate at each release.\n\n"
        )
        out.write("\n".join(blocks))
    print(f"wrote {OUT}: {len(blocks)} packages, {len(missing)} without license files")
    for m in missing:
        print(f"  note: {m}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
